# Generated by Django 6.0.1 on 2026-01-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(null=True)),
                ('Roll', models.PositiveIntegerField(null=True)),
                ('Address', models.TextField(null=True)),
                ('Image', models.ImageField(null=True, upload_to='img/')),
                ('Date', models.DateTimeField(null=True)),
            ],
        ),
    ]
