# Generated by Django 6.0.1 on 2026-01-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empolyee_name', models.CharField(null=True)),
                ('employee_photo', models.ImageField(null=True, upload_to='img/')),
                ('basic_salary', models.IntegerField(null=True)),
                ('har', models.IntegerField(null=True)),
                ('bonus', models.IntegerField(null=True)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('gross_salary', models.IntegerField(null=True)),
                ('net_salary', models.IntegerField(null=True)),
            ],
        ),
    ]
