# Generated by Django 6.0 on 2026-01-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_salarymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='subjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('dept_type', models.CharField(choices=[('CSE', 'CSE'), ('EEE', 'EEE'), ('CIVIL', 'CIVIL')], max_length=10, null=True)),
                ('credit', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
