# Generated by Django 6.0 on 2026-01-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='grade',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='mark',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
