# Generated by Django 6.0 on 2026-01-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_productmodel_grade_productmodel_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='grade',
            field=models.TextField(null=True),
        ),
    ]
