# Generated by Django 6.0 on 2026-01-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_productmodel_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='grade',
            field=models.CharField(null=True),
        ),
    ]
