# Generated by Django 6.0 on 2026-01-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_productmodel_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='slaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hra', models.CharField(max_length=200)),
                ('basic_salary', models.IntegerField(null=True)),
                ('overtime_hours', models.IntegerField(null=True)),
                ('hra_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('da_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('ta_persent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('DA', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('TA', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('overtime', models.IntegerField(null=True)),
                ('bouns', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('GrossSalary', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
