# Generated by Django 6.0 on 2026-01-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_slarymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='picture',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
