# Generated by Django 6.0 on 2026-01-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='picture',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
