# Generated by Django 6.0 on 2026-01-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(null=True)),
                ('Course', models.CharField(null=True)),
                ('Total_Marks', models.PositiveIntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='imag/')),
            ],
        ),
    ]
