# Generated by Django 6.0.1 on 2026-01-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='salaryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Overtime', models.IntegerField(null=True)),
                ('Bouns', models.IntegerField(null=True)),
                ('DA', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('TA', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('Basic_salary', models.IntegerField(null=True)),
                ('HRA', models.TextField(null=True)),
                ('overtime_hours', models.IntegerField(null=True)),
                ('ta_percent', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('da_percent', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('her_percent', models.DecimalField(decimal_places=2, max_digits=50, null=True)),
                ('Gross_salary', models.IntegerField(null=True)),
            ],
        ),
    ]
