# Generated by Django 6.0.1 on 2026-01-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salarymodel',
            name='DA',
        ),
        migrations.RemoveField(
            model_name='salarymodel',
            name='HRA',
        ),
        migrations.RemoveField(
            model_name='salarymodel',
            name='Overtime',
        ),
        migrations.RemoveField(
            model_name='salarymodel',
            name='TA',
        ),
    ]
