# Generated by Django 6.0 on 2026-01-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_salarymodel_da_remove_salarymodel_hra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarymodel',
            name='Picture',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
    ]
